FaziletOto.MVC.UI/Controllers/AdminCommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class AdminCommonController : Controller
    {
        public PartialViewResult RenderSidebar(string pageTitle)
        {
            return PartialView("~/Views/Shared/AdminSidebarPartial.cshtml",pageTitle);
        }
    }
}

FaziletOto.MVC.UI/Controllers/AdminHomeController.cs
using FaziletOto.BLL.Data.EF.Service;
using FaziletOto.DOMAIN.Entities;
using FaziletOto.DTOs.AdminSummaryDTOs;
using FaziletOto.MVC.UI.Attributes;
using FaziletOto.MVC.UI.Models.ModelViews;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    [Authentication]  
    public class AdminHomeController : Controller
    {
        readonly private IUserService userManager;
        readonly private IProductCategoryService categoryManager;
        readonly private IProductService productManager;
        readonly private IProductAndCategoryService relationManager;


        public AdminHomeController(IUserService userManager, IProductCategoryService categoryManager, IProductService productManager, IProductAndCategoryService relationManager)
        {
            this.userManager = userManager;
            this.categoryManager = categoryManager;
            this.productManager = productManager;
            this.relationManager = relationManager;
        }

        [Authorization(Roles = "Admin,Salesman,StockKeeper")]
        [HttpGet]
        public ActionResult AdminHomePage()
        {
            CategorySummaryDto categorySummary = new CategorySummaryDto();
            var categories = categoryManager.Gets(x => x.IsActive && !x.IsDeleted, "ProductAndCategories.Product").Data;
            foreach (var category in categories)
            {
                CategorySubSummaryDto categorySubSummary = new CategorySubSummaryDto();
                categorySubSummary.CategoryName = category.Name;
                categorySubSummary.RelatedProductCount = category.ProductAndCategories.Where(x => x.IsActive && !x.IsDeleted).ToList().Count;
                categorySummary.CategorySubSummaryDtos.Add(categorySubSummary);
            }

            AdminSummaryMV adminSummaryMV = new AdminSummaryMV()
            {
                UserSummaryDto = userManager.UserSummary(),
                ProductSummaryDto = productManager.ProductSummary(),
                CategorySummaryDto = categorySummary,
            };

            return View(adminSummaryMV);
        }
    }
}

FaziletOto.MVC.UI/Controllers/CommonController.cs
using FaziletOto.BLL.Data.EF.Service;
using FaziletOto.DOMAIN.Entities;
using FaziletOto.MVC.UI.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FaziletOto.MVC.UI.Controllers
{
    public class CommonController : Controller
    {

        private readonly IUserService userManager;

        public CommonController(IUserService _userManager)
        {
            userManager = _userManager;
        }

        public PartialViewResult RenderNavbar()
        {
            User user = null;
            if (UserSession.CurrentUser != null)
            {
                user = UserSession.CurrentUser;
            }
            return PartialView("~/Views/Shared/NavbarPartial.cshtml", user);
        }
    }
}

FaziletOto.MVC.UI/Views/Shared/AdminMainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Partial("~/Views/Shared/ExtensionPartial.cshtml")
    @RenderSection("Style", false)
</head>
<body>
    <div>
        @{Html.RenderAction("RenderSidebar", "AdminCommon", new {pageTitle = (string)ViewBag.Title });}
    </div>
    <div id="main">
        <div class="w3-teal">
            <div class="row bg-dark m-0 p-0">
                <button id="openNav" class="btn btn-dark w3-xlarge float-left" onclick="w3_open()">&#9776;</button>
                <div class="w3-container float-left">
                    <h2>@ViewBag.Title</h2>
                </div>
            </div>
        </div>
        <div class="w3-container">
            @RenderBody()
        </div>
    </div>
    @RenderSection("Script", false)
</body>
</html>

FaziletOto.MVC.UI/Views/Shared/AdminSidebarPartial.cshtml
@model string

<div class="w3-sidebar w3-bar-block w3-card w3-animate-left bg-dark m-0 p-0" style="display:none" id="mySidebar">
    <div class="row modal-open p-0 mb-2">
        <div class="col-12">
            <button class="btn btn-dark w3-large float-right" onclick="w3_close()">
                <span style="font-size:1.6em">&times;</span>
            </button>
        </div>       
    </div>   
    <div class="row text-left ml-3 mr-3" style="border:2px groove #ffc107; border-right:1px none #343a40; border-left:0">
        <ul class="text-white w-100 p-3 mt-1 mb-1" style="list-style-type:none">
            <li class="text-center"><img class="img-thumbnail rounded-circle" src="@(UserSession.CurrentUser.PhotoPath)" height="80" width="80"/></li>
            <li><span style="color:#ffc107">Kullanıcı :</span>  @UserSession.CurrentUser.Name @UserSession.CurrentUser.Surname</li>
            <li><span style="color:#ffc107">Kullanıcı ID:</span> @UserSession.CurrentUser.ID</li>
            <li class="mt-1"><span style="color:#ffc107">Yetkiler :</span> 
                <ul class="text-white" style="list-style-type:square">
                    @(UserSession.CurrentUser.IsAdmin? Html.Raw("<li>Admin</li>") : Html.Raw(""))
                    @(UserSession.CurrentUser.IsSalesman? Html.Raw("<li>Satış Personeli</li>") : Html.Raw(""))
                    @(UserSession.CurrentUser.IsStockKeeper? Html.Raw("<li>Stok Personeli</li>") : Html.Raw(""))
                </ul>
            </li>
        </ul>
    </div>
    <a href="@Url.Action("AdminHomePage","AdminHome")" class="w3-bar-item w3-button text-decoration-none text_Sidebar mt-3 @(Model.Contains("Anasayfa")?"text-warning":"")"><span class="fa fa-home"></span> Anasayfa</a>
    <div class="btn-group dropdown w-100">
        <a href="@Url.Action("AdminUserPage","AdminUser")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Kullanıcılar")?"text-warning":"")"><span class="fa fa-user"></span> Kullanıcılar</a>
        <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-chevron-down text-white"></span>
        </button>
        <div class="dropdown-menu bg-dark" style="color:black">
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminUserAddPage","AdminUser")">Ekle</a>
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminUserArrangePage","AdminUser")">Düzenle</a>
        </div>
    </div>

    <div class="btn-group dropdown w-100">
        <a href="@Url.Action("AdminCategoryPage","AdminCategory")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Kategori")?"text-warning":"")"><span class="fa fa-file"></span> Ürün Kategori</a>
        <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-chevron-down text-white"></span>
        </button>
        <div class="dropdown-menu bg-dark" style="color:black">
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminCategoryAddPage","AdminCategory")">Ekle</a>
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminCategoryArrangePage","AdminCategory")">Düzenle</a>
        </div>
    </div>

    <div class="btn-group dropdown w-100">
        <a href="@Url.Action("AdminProductHomePage","AdminProduct")" class="w3-bar-item w3-button text-decoration-none text_Sidebar @(Model.Contains("Ürün")&&!Model.Contains("Kategori")?"text-warning":"")"><span class="fa fa-automobile"></span> Ürün</a>
        <button type="button" class="btn rounded" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="fa fa-chevron-down text-white"></span>
        </button>
        <div class="dropdown-menu bg-dark" style="color:black">
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminProductAddPage","AdminProduct")">Ekle</a>
            <a class="dropdown-item w-100 text_SidebarSub" href="@Url.Action("AdminProductArrangePage","AdminProduct")">Düzenle</a>
        </div>
    </div>
</div>

FaziletOto.MVC.UI/Views/Shared/ExtensionPartial.cshtml
<link href="~/Content/bootstrapCSS/bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/CSS/AdminSidebar.css" rel="stylesheet" />
<link href="~/Content/fontAwesome/css/font-awesome.css" rel="stylesheet" />


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="~/Content/Jquery/jquery.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="~/Content/JS/AdminSidebar.js"></script>
<script>var _tooltip = jQuery.fn.tooltip;</script>
<script type="application/javascript" src="/js/jquery-ui.js"></script>
<script>jQuery.fn.tooltip = _tooltip;</script>

FaziletOto.MVC.UI/Views/Shared/MainLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Html.Partial("ExtensionPartial")
</head>
<body>
    @{Html.RenderAction("RenderNavbar", "Common");}
    @RenderBody()
</body>
</html>

FaziletOto.MVC.UI/Views/Shared/NavbarPartial.cshtml
@model User

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            @{
                if (Model == null)
                {
                    <li class="nav-item">
                        <button type="button" class="btn btn-primary nav-item" data-toggle="modal" data-target="#loginModal">
                            Login
                        </button>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <span class="nav-link" style="cursor:default">@Model.Username</span>
                    </li>
                    if (Model.IsAdmin || Model.IsSalesman || Model.IsStockKeeper)
                    {
                        <li class="nav-item">
                            <span class="nav-link" style="cursor:default"> |</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("AdminHomePage","AdminHome")">Yönetim</a>
                        </li>
                    }
                    <li class="nav-item">
                        <span class="nav-link" style="cursor:default"> |</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("SignOutPost","Account")">Sign Out</a>
                    </li>
                }
            }

        </ul>
    </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center w-100">
                <h5 class="modal-title text-center w-100" id="loginModalLabel">Login</h5>
            </div>
            <div class="modal-body">
                @{Html.BeginForm("LoginPost", "Account", FormMethod.Post, new { @class = "form-group" });}
                @Html.AntiForgeryToken()
                <input name="Email" class="form-control w-100" type="email" required="required" placeholder="E-posta" minlength="8" maxlength="100"/>
                <input name="Password" class="form-control w-100" type="password" required="required" placeholder="Şifre" minlength="8" maxlength="20"/>
                <div class="w-100 text-center">
                    <input class="btn btn-primary w-50" type="submit" />
                </div>
                <div class="text-justify text-danger">
                    @{
                        if (TempData["LoginResult"] != null)
                        {
                            @Html.Raw(TempData["LoginResult"])
                        }
                    }
                </div>
                @{Html.EndForm();}
            </div>
        </div>
    </div>
</div>